version: '3.7'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: walletdb
    container_name: walletdb
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: walletredis

  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: [ "/wallet/app.sh" ]
    ports:
      - 9000:8000

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
