"""add transaction logic

Revision ID: 5fb3159c9853
Revises: 60c09320cab3
Create Date: 2024-11-13 11:01:21.954160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb3159c9853'
down_revision: Union[str, None] = '60c09320cab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('sender_wallet_id', sa.Integer(), nullable=False))
    op.add_column('transaction', sa.Column('receiver_wallet_id', sa.Integer(), nullable=False))
    op.drop_constraint('transaction_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['receiver_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['sender_wallet_id'], ['id'])
    op.drop_column('transaction', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_wallet_id_fkey', 'transaction', 'wallet', ['wallet_id'], ['id'])
    op.drop_column('transaction', 'receiver_wallet_id')
    op.drop_column('transaction', 'sender_wallet_id')
    # ### end Alembic commands ###
