"""drop table again

Revision ID: 86bad400329e
Revises: 330409c2fab1
Create Date: 2024-12-03 22:21:49.446940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86bad400329e'
down_revision: Union[str, None] = '330409c2fab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transaction', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction', 'type',
               existing_type=postgresql.ENUM('INCOME', 'OUTCOME', name='transactiontypeenum'),
               nullable=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.alter_column('wallet', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=False)
    op.alter_column('wallet', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.alter_column('wallet', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wallet', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=True)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.alter_column('transaction', 'type',
               existing_type=postgresql.ENUM('INCOME', 'OUTCOME', name='transactiontypeenum'),
               nullable=True)
    op.alter_column('transaction', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
