"""Added created_date column

Revision ID: bff1ecb96489
Revises: 826f0fbdc7b8
Create Date: 2024-12-21 14:44:05.913824

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff1ecb96489'
down_revision: Union[str, None] = '826f0fbdc7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('wallet', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.alter_column('wallet', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'currency',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               existing_nullable=False)
    op.drop_column('wallet', 'created_date')
    op.drop_column('user', 'created_date')
    op.drop_column('transaction', 'created_date')
    # ### end Alembic commands ###
