"""update user model

Revision ID: 1ec1d7a83235
Revises: 63b2f80fa350
Create Date: 2024-11-10 09:36:16.230524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec1d7a83235'
down_revision: Union[str, None] = '63b2f80fa350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usename', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['usename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'usename')
    # ### end Alembic commands ###
